### ISSUE TITLE
Plural forms

### ISSUE THREAD

**Issue by marmistrz** [foolab/cameraplus#51]
The translations may be a little quirky unless cameraplus supports this: https://doc.qt.io/archives/qq/qq19-plurals.html

**Comment by foolab** [comment]
Which strings are causing problems?

**Comment by marmistrz** [comment]
For example: `%1 seconds`. This would be `1 sekunda`, `2 sekundy` or `5 sekund`, `31 sekund` but `32 sekundy`. (singular, paucal, plural). Languages such as Polish or Russian work that way.

**Comment by foolab** [comment]
Is that the only string? Or should I check all the translatable strings? :)

**Comment by marmistrz** [comment]
`Capture %1 shots`
`%1 seconds interval`
`Capture after %1 seconds`

I guess it's all, if I come across something else, I'll raise a separate issue if that one's closed.

**Comment by foolab** [comment]
It's now fixed in git master. Could you please update the polish translation?
