### ISSUE TITLE
I can not install any more cameraplus on sf3.3

### ISSUE THREAD

**Issue by carlosgonz0** [foolab/cameraplus#56]
I am using cameraplus from n9, it would be nice to revive this wonderfull app for people who love camera+.

**Comment by foolab** [comment]
What exactly is the problem?

**Comment by carlosgonz0** [comment]
![Captura_20191129_004](https://user-images.githubusercontent.com/45316884/69879671-09617e00-1296-11ea-87d7-6d492b827631.png)

**Comment by carlosgonz0** [comment]
The screenshot say: can't find libsnd.file.so

**Comment by carlosgonz0** [comment]
HI Mohammed 
Any news??
